// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvzgfHkHJDX4p1pn4m_LYekVIsIxY5Sn4',
    appId: '1:566270806232:web:a65cc945929a0fc2476fad',
    messagingSenderId: '566270806232',
    projectId: 'app-unicv-ff2f9',
    authDomain: 'app-unicv-ff2f9.firebaseapp.com',
    storageBucket: 'app-unicv-ff2f9.appspot.com',
    measurementId: 'G-VLEDDSPD87',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARjkFfkrlV-yztKMEhP3jLfuXYFp7xmpU',
    appId: '1:566270806232:android:2e8711d4118e24cd476fad',
    messagingSenderId: '566270806232',
    projectId: 'app-unicv-ff2f9',
    storageBucket: 'app-unicv-ff2f9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsOnHhw8b0KX7kgVlA3FQCOadh_YeG760',
    appId: '1:566270806232:ios:16f3be892e02ca20476fad',
    messagingSenderId: '566270806232',
    projectId: 'app-unicv-ff2f9',
    storageBucket: 'app-unicv-ff2f9.appspot.com',
    iosBundleId: 'com.example.appunicv',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsOnHhw8b0KX7kgVlA3FQCOadh_YeG760',
    appId: '1:566270806232:ios:16f3be892e02ca20476fad',
    messagingSenderId: '566270806232',
    projectId: 'app-unicv-ff2f9',
    storageBucket: 'app-unicv-ff2f9.appspot.com',
    iosBundleId: 'com.example.appunicv',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvzgfHkHJDX4p1pn4m_LYekVIsIxY5Sn4',
    appId: '1:566270806232:web:d8a3dab9c99fe54f476fad',
    messagingSenderId: '566270806232',
    projectId: 'app-unicv-ff2f9',
    authDomain: 'app-unicv-ff2f9.firebaseapp.com',
    storageBucket: 'app-unicv-ff2f9.appspot.com',
    measurementId: 'G-20VVP3EYVR',
  );
}
